/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class Bai17_GiaiPTB2 extends javax.swing.JFrame {

    /**
     * Creates new form Bai17_GiaiPTB2
     */
    public Bai17_GiaiPTB2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbla = new javax.swing.JLabel();
        lblb = new javax.swing.JLabel();
        txtsoa = new javax.swing.JTextField();
        txtsob = new javax.swing.JTextField();
        lblc = new javax.swing.JLabel();
        txtsoc = new javax.swing.JTextField();
        BTTinh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKQ = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbla.setText("Nhap a");
        lbla.setName("lbla"); // NOI18N

        lblb.setText("Nhap b");
        lblb.setName("lblb"); // NOI18N

        txtsoa.setName("txtsoa"); // NOI18N
        txtsoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoaActionPerformed(evt);
            }
        });

        txtsob.setName("txtsob"); // NOI18N

        lblc.setText("Nhap c");
        lblc.setName("lblbc"); // NOI18N

        txtsoc.setName("txtsoc"); // NOI18N

        BTTinh.setText("Tính ");
        BTTinh.setActionCommand("Tính");
        BTTinh.setName("BTTinh"); // NOI18N
        BTTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTinhActionPerformed(evt);
            }
        });

        jLabel1.setText("Giải phương trình bậc 2 siêu cấp vip pro ");

        txtKQ.setColumns(20);
        txtKQ.setRows(5);
        txtKQ.setName("txtKQ"); // NOI18N
        jScrollPane1.setViewportView(txtKQ);

        jLabel2.setText("Kết quả");
        jLabel2.setName("lblKQ"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblb)
                            .addComponent(lblc)
                            .addComponent(lbla, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(txtsoc)
                            .addComponent(txtsoa)
                            .addComponent(txtsob))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbla)
                    .addComponent(txtsoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblb)
                    .addComponent(txtsob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTinhActionPerformed
        // TODO add your handling code here:
        double x1, x2, delta;
        double a = Double.parseDouble(txtsoa.getText());
        //System.out.println("Nhap so a: "+a);
        double b = Double.parseDouble(txtsob.getText());
        //System.out.println("Nhap so b: "+b);
        double c = Double.parseDouble(txtsoc.getText());
        //System.out.println("Nhap so c: "+c);
        if (a == 0) {
            if (b == 0) {
                if (c != 0) {
                    txtKQ.setText("Phương trình vô nghiệm");//System.out.println("Phương trình vô nghiệm");
                } else {
                    txtKQ.setText("Phương trình có vô số nghiệm");//System.out.println("Phương trình có vô số nghiệm");
                }
            } else {
                x1 = x2 = - c / b;
                txtKQ.setText("Phương trình có nghiệm x = " + x1);//System.out.println("Phương trình có nghiệm x = "+x1);
            }
        } else {
            delta = b * b - 4 * a * c;
            if (delta < 0) {
                txtKQ.setText("Phương trình vô nghiệm");//System.out.println("Phương trình vô nghiệm");
            }
        
        else if(delta == 0) {

                    x1 = x2 = -b / (2 * a);
                    txtKQ.setText("Phương trình có nghiệm kép x1 = x2 =" + x1);//System.out.println("Phương trình có nghiệm kép x1 = x2 ="+x1);
                } 
                    else {
                    x1 = (-b + Math.sqrt(delta)) / (2 * a);
                    x2 = (-b - Math.sqrt(delta)) / (2 * a);
                    txtKQ.append("Phương trình có 2 nghiệm phân biệt\n");//System.out.println("Phương trình có 2 nghiệm phân biệt");
                    txtKQ.append("x1 = " + x1+"\n");//System.out.println("x1 = "+x1);
                    txtKQ.append("x2 = " + x2+"\n");//System.out.println("x2 = "+x2);
                }
        }

//txtKQ.append();

    }//GEN-LAST:event_BTTinhActionPerformed

    private void txtsoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai17_GiaiPTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai17_GiaiPTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai17_GiaiPTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai17_GiaiPTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai17_GiaiPTB2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lblb;
    private javax.swing.JLabel lblc;
    private javax.swing.JTextArea txtKQ;
    private javax.swing.JTextField txtsoa;
    private javax.swing.JTextField txtsob;
    private javax.swing.JTextField txtsoc;
    // End of variables declaration//GEN-END:variables
}
